apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: storage-ic
spec:
  secretName: storage-interconnect-secret
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  subject:
    organizations:
      - yandex
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - '*.default.svc.cluster.local'
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
